[[Categories]]
name = "world"
target_percentage=0.75

[[Categories]]
name = "bonds"
target_percentage=0.25

[[Securities]]
name = "iShares Core MSCI World UCITS ETF USD (Acc)"
symbol = "IWDA.AS"
url = "https://trader.degiro.nl/trader/#/products/846772"
amount = 859
latest_value = 0.0
latest_value_time = 0
target_percentage = 1.0
category = "world"

[[Securities]]
name = "iShares BRIC 50 UCITS ETF USD (Dist)"
symbol = "BRIC.AS"
url = "https://trader.degiro.nl/trader/#/products/846748"
amount = 171
latest_value = 0.0
latest_value_time = 0
target_percentage = 0.0
category = "world"

[[Securities]]
name = "iShares Euro Inflation Linked Government Bond UCITS ETF"
symbol = "IBCI.AS"
url = "https://trader.degiro.nl/trader/#/products/846726"
amount = 19
latest_value = 0.0
latest_value_time = 0
target_percentage = 1.0
category = "bonds"

[[Securities]]
name = "iShares Govt Bond 3-5yr UCITS ETF EUR (Dist)"
symbol = "IBGX.AS"
url = "https://trader.degiro.nl/trader/#/products/846740"
amount = 120
latest_value = 0.0
latest_value_time = 0
target_percentage = 0.0
category = "bonds"
